
name: Test Go Versions

on:
  push:
    

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
        go-version: ['1.19.0', '1.22.7', '1.22.8', '1.23.1', '1.23.2']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: priyagupta108/setup-go@create_release
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./...
