name: Test Go with self-hosted

on:
  push:
jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

  

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20.1'
        # cache: false
        
    - name: Verify Go version
      run: go version

    # - name: Cache Go modules
    #   uses: actions/cache@v4
    #   with:
    #     path: |
    #       ~/.cache/go-build
    #       # Cache Go modules
    #       ~/go/pkg/mod
    #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    #     restore-keys: |
    #       ${{ runner.os }}-go-


    

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./...
