name: build

on: [push]

jobs:
  golang:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Install Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: 1.21.10

      - name: Install Go
        run: |
         GO_VERSION=1.21.12
         sudo rm -rf /usr/local/go
         curl -fsSL "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz" | sudo tar -C /usr/local -xz
         echo 'export PATH=/usr/local/go/bin:$PATH' >> $GITHUB_ENV
         echo 'export PATH=$HOME/go/bin:$PATH' >> $GITHUB_ENV
    
      - name: Verify Go installation
        run: go version


      - name: Build shared library
        run: go build -o lib.so -buildmode=c-shared

      - name: Test shared library
        run: python run.py
        

      - name: Save shared library as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: lib-${{ matrix.os }}.so
          path: lib-${{ matrix.os }}.so
