name: build

on: [push]

jobs:
  golang:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
      - name: Checkout gpnutil
        uses: actions/checkout@v4
      - name: Install Latest GCC
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y gcc
          sudo apt-get install -y gcc
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5
          cache: false
      - name: Go version
        run: go version
    
      - name: Install Go
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.5
      - name: Build
        run: |
         
          go build -x -o lib.so -buildmode=c-shared
      - name: Test shared library
        run: python3 run.py

      - name: Save shared library as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: lib-${{ matrix.os }}
          path: lib.so
