name: custom-go-download-positive
on: [push]

jobs:

  # POSITIVE: env var support.
  envvar_base_url_all_os:
    name: env var base url (aka.ms) exact patch
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: gdams/setup-go@msgo
        env:
          GO_DOWNLOAD_BASE_URL: 'https://aka.ms/golang/release/latest'
        with:
          go-version: '1.25.0'
      - run: go version

