name: test-aka-ms-direct-download
on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup Go from aka.ms (custom base URL)
        uses: gdams/setup-go@msgo
        with:
          go-version: '1.25.0'
          go-download-base-url: 'https://aka.ms/golang/release/latest'
          cache: false

      - run: go version
