name: major_minor-download
on: [push]

jobs:
  major_minor:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6
      - name: Test major.minor version
        uses: gdams/setup-go@msgo
        with:
          go-version: '1.20'
          go-download-base-url: 'https://aka.ms/golang/release/latest'  

      - name: Check Go version
        run: go version