name: Test cache-hit

on:
  push:

jobs:
  repro:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6

      - name: setup-go (PR)
        id: setupgo
        uses: lmvysakh/setup-go@fileexists_resolution
        # uses: actions/setup-go@v6
        with:
          go-version: "1.22.x"
          cache: true

      # Typical pattern that becomes risky if cache-hit is "true" just because dirs are non-empty.
      - name: Download deps (should run when key changes / cache miss)
        if: steps.setupgo.outputs.cache-hit != 'true'
        run: go mod download

      - name: Build/Test
        run: go test ./...