name: custom-go-download-positive
on: [push]

jobs:

  # POSITIVE: trailing slash is handled
  trailing_slash:
    name: trailing slash base url
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: gdams/setup-go@msgo
        with:
          go-version: '1.25.0'
          go-download-base-url: 'https://aka.ms/golang/release/latest/'
      - run: go version

